apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "ping.frontend.fullname" . }}-hpa
spec:
  maxReplicas: {{ .Values.frontendhpa.maxReplicas }}
  minReplicas: {{ .Values.frontendhpa.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ template "ping.frontend.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.frontendhpa.targetCPUUtilizationPercentage }}